
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: |
          docker-compose up -d --build
          docker exec nodeapp npm test
          
      - name: List nginx directories
        run: docker exec nginx ls

      - name: Stop containers
        if: always()
        run: docker-compose -f down
